### ISSUE TITLE
V1.0.7, failure in syncing articles with Stand-alone mode

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#483]
**Describe the bug**
Running Raven Reader V1.0.7 on Win 10 64-Bit. Raven Reader tells me that it has 4652 items (articles) after a couple of syncs yesterday. However, today Raven Reader fails to sync articles from my feeds. I'm using the Stand-alone mode. When I bring up Raven Reader, it shows the "Syncing..." message, but it never goes away even after 15 to 20 minutes. When I finally select a category/folder, the "Syncing..." message goes away and again Raven Reader tells me that I have 4652 items. All articles in all feeds are old -- from yesterday.
Also I'm wondering why the app provides no progress bars while it is syncing articles. Usually -- in case it works, it takes a couple of minutes with my voluminous feeds/articles, so it would be quite useful to have progress bars for the syncing process.
**To Reproduce**
My feed OPML is attached -- hopefully it can help detect the bug after some syncs with articles reaching 4652.
**Expected behavior**
Natuarally with each restart or with each manual attempt it is expected to have all feeds synced.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome V86
[feeds.zip](https://github.com/hello-efficiency-inc/raven-reader/files/5398179/feeds.zip)

**Comment by mrgodhani** [comment]
Standalone should be syncing. It syncs at 5 mins interval by default you can change settings on settings modal.

In v1.0.8 you will get a notification when synced now.

**Comment by amirsol81** [comment]
@mrgodhani I'm familiar with the 5-minute refresh setting, and am indeed using it. But the issue is that with V1.0.7, or maybe with a limite of 4652 articles cached, Raven Reader never refreshes my feeds -- neither manually by selecting the "Refresh all feeds" button nor automatically -- every 5 minutes.
I'll try V1.08 later today.

**Comment by mrgodhani** [comment]
@amirsol81  It would only sync new articles from the feed. So that's the difference between what's new and what's already there. If there is nothing there then it won't add any. Notification should help as it would announce how many new articles are added.

**Comment by amirsol81** [comment]
@mrgodhani That's true. But my comparison indicates that many of my feeds do contain new items as other RSS readers display new articles for them.
I synced last time with V1.0.6 on Saturday and everything worked fine -- both automatically and manually. But a day later and with V1.0.7, I had zero syncing despite attempting several times -- closing/restarting the app or selecting the "Refresh all" button manually. I'll try V1.0.8 at home later today on my home machine.

**Comment by amirsol81** [comment]
@mrgodhani BTW the download link for V1.0.8 doesn't work: https://download.helloefficiency.com/ravenreader/Raven%20Reader%20Setup%201.0.8.exe
I get the following error message in Internet Download Manager: Raven Reader Setup 1.0.8.exe
The server replies that you don't have permissions to download 
this file.
Details:
HTTP/1.1 403 Forbidden

OK

**Comment by mrgodhani** [comment]
@amirsol81  should be working now

**Comment by amirsol81** [comment]
@mrgodhani  Just checked, and download still doesn't work -- the same error message.

**Comment by mrgodhani** [comment]
@amirsol81  Cache is purged try again https://download.helloefficiency.com/ravenreader/Raven%20Reader%20Setup%201.0.8.exe

**Comment by amirsol81** [comment]
@mrgodhani Third time lucky! It works now. Thanks.
