### ISSUE TITLE
V1.0.8: Raven Reader doesn't import OPML files on a Win 7 64-Bit machine

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#484]
**Describe the bug**
Here I'm running Windows 7 64-Bit at work, and Raven Reader V1.0.8 doesn't import my OPML file (attached) despite several attempts. I even uninstalled V1.0.8, removed all remaining folders manually, re-installed V1.0.8, and tried importing, but nothing gets imported at all.
**To Reproduce**
Simply import my provided OPML file.
**Expected behavior**
Raven Reader should import the OPML file.

**Desktop (please complete the following information):**
 - OS: Windows 7 64-Bit
 - Browser: Google Chrome V86

**Additional context**
I'll try V1.0.8 on my home Win 10 Pro 64-Bit machine at home later today to see if the same happens there. Also I'd be curious to see if V1.0.8 would resolve my syncing issues with Win 10.
[feeds.zip](https://github.com/hello-efficiency-inc/raven-reader/files/5400046/feeds.zip)

**Comment by mrgodhani** [comment]
This is because one of the source links is not secure and is not able to verify SSL certificate. Will look into this issue and fix in next release. Your older opml export I was able to still export.

**Comment by amirsol81** [comment]
@mrgodhani That would be truly appreciated. So looking forward to the next release.

**Comment by mrgodhani** [comment]
Resolved in v1.0.9

**Comment by amirsol81** [comment]
@mrgodhani I'm running V1.0.9 now, but my provided OPML file still fails to be loaded/imported, or at least I don't see my feeds in Raven Reader at all. I even uninstalled V1.0.8 and removed the remaining folders manually, but reinstalling the app didn't resolve the issue. This is on a Win 7 64-Bit machine at work, so I should check my Win 10 Pro machine at home, too.

**Comment by mrgodhani** [comment]
@amirsol81 There would  be a bit delay as it tries to parse unsecured urls i.e one without https

**Comment by amirsol81** [comment]
@mrgodhani On my Windows 10 Pro 64-Bit machine at home, V1.0.9 does the import successfully and it just takes a couple of seconds -- literally. But the issue persists on my Win 7 64-Bit at work. Maybe other factors are involved there -- I don't know. So I'll keep investigating that.
BTW the app has really become faster -- folders can be collapsed/expanded much more quickly. However, it seems that V1.0.9 just displays 10 articles from each feed even if that feed fetches, say, 60 articles. For instance, the following feed is capable of providing up to 150 articles at a time, but Raven Reader V1.0.9 displays 10 articles -- not enough at all: http://www.dailymail.co.uk/wires/index.rss
I think this should be either reverted to the original (unlimited number of articles) or be adjusted by the user. Most of my feeds provide 15 to 25 articles per refresh, and some offer even 50 articles, but I can't view them given the new limitation. Please kindly alter this new behavior.

**Comment by amirsol81** [comment]
@mrgodhani Ah, I just noticed the "Load more" button which actually loads some more articles each time it is pressed. That's good, but I suggest setting the limit to 25 instead of the current 10 new articles as many feeds provide 15 to 25 articles per each refresh.

**Comment by amirsol81** [comment]
@mrgodhani This issue still persists though in a subtle form. Now Raven Reader always syncs articles when it is opened. However, if it is kept running in the background and is later brought in the foreground, it keeps the "Syncing" message without either finishing syncing or displaying the previous articles. Even the Feed list/category isn't displayed unless the app is closed (shut down) and restarted. Quite interestingly, the notifications for fetched articles keep coming, but Raven Reader V1.0.9 doesn't finish syncing unless it is restarted. I'm also attaching a screenshot. This is inconvenient as one needs to keep closing/restarting the app in order to make sure feeds/articles are always synced.
![Raven Reader](https://user-images.githubusercontent.com/34389170/96769937-b41de600-13ec-11eb-9540-13894f0709bf.jpg)

**Comment by mrgodhani** [comment]
@amirsol81 sounds odd. Is that your work laptop again? It could be work firewalls blocking it but I will test it in Windows. There is small delay on loading feeds with 5000 articles or big data. But should show up unless there is error in feed sync.

**Comment by amirsol81** [comment]
@mrgodhani No, this is my Win 10 Pro home machine. So far I have seen it 3 times, and each time Raven Reader has been running in the background for a while (in the Task Tray), and giving it the focus has displayed the glitch. That is, the "Syncing" message doesn't go away even if I wait for 10 minutes. Under normal circumstances, each sync is complete in 30 seconds or so -- maybe a bit longer.

**Comment by mrgodhani** [comment]
Sounds like windows only issue I will test it

**Comment by amirsol81** [comment]
@mrgodhani Thanks. So make sure the app is in the background -- I mean press ALT+F4 to close Raven Reader and send it to the Task Tray, and let it stay there for a while. Also my provided OPML file here can help.

**Comment by mrgodhani** [comment]
Hm ye I didn't reproduce the situation about things disappearing using your previous OPML. One attached to this ticket works fine on Mac but seems like windows still reject unsecured feed links that one of your link from OPML has

**Comment by amirsol81** [comment]
@mrgodhani So may I know which feed URL is unsecured? I just took a look, and many of my feed links are unsecured -- even many NPR and CNN ones. So is every link in the form of http://... unsecured? I wanted to remove the unsecured link(s) to see its effect on the issue I'm experiencing.
