### ISSUE TITLE
Raven Reader fails to display article summaries

### ISSUE THREAD

**Issue by amirsol81** [hello-efficiency-inc/raven-reader#488]
**Issue**
Oftentimes feeds, even those which hide their full content, display one or two lines of text which serves as their summary. This way readers can gain an understanding of what the article is about. However, Raven Reader doesn't display article summaries -- under article titles -- at all.
For instance, the following 2 RSS feeds display summaries for all articles. But Raven Reader doesn't display them:
Wired Top Stories: http://feeds.wired.com/wired/index
Wires Mail Online: http://www.dailymail.co.uk/wires/index.rss

**To Reproduce**
Simply take a look at your article titles. You'll see no article summaries near the titles.

**Expected behavior**
Article summaries should always be displayed -- if available.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-Bit V2004
 - Browser: Google Chrome
 - Version: 86

**Additional context**
Raven Reader V1.0.9.0

**Comment by mrgodhani** [comment]
fixed in v1.0.10

**Comment by amirsol81** [comment]
@mrgodhani Thanks! Will try it today.

**Comment by amirsol81** [comment]
@mrgodhani I'm running the latest *.10 release, but the Article Summary bug is still there. Now an article summary is displayed once an article is selected, so one should select the "Full content" button to view the whole article. But it would be better and more efficient if, like many other RSS Readers, Raven Reader could display article summaries inside the article list -- below each title. This way we could check both the title and the summary without having to select the title first, and accessing the full content wouldn't need an extra step of selecting the "Full Content" button..

**Comment by amirsol81** [comment]
@mrgodhani Having spent more time with v1.0.10, may I again request that article summaries, if exist, be displayed automatically in the list of articles, near each article title? The current implementation (I mean displaying an article summary only when a title is selected, resulting in the delayed display of the full content) isn't really useful IMO.
